import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%PEBBLE_AGENT_HOOK_PORT%"=="" if defined PEBBLE_AGENT_HOOK_ENDPOINT if exist "%PEBBLE_AGENT_HOOK_ENDPOINT%" call "%PEBBLE_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%PEBBLE_AGENT_HOOK_TOKEN%"=="" if not "%PEBBLE_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      'if "%PEBBLE_AGENT_HOOK_PORT%"=="" exit /b 0',
      'if "%PEBBLE_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'if "%PEBBLE_PANE_KEY%"=="" exit /b 0',
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\pebble-dev\\agent-hooks" for /r "%APPDATA%\\pebble-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%PEBBLE_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\pebble\\agent-hooks" for /r "%APPDATA%\\pebble\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%PEBBLE_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set PEBBLE_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%PEBBLE_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    '__pebble_read_ancestor_var() {',
    '  __pebble_name="$1"',
    '  __pebble_pid="${PPID:-}"',
    '  while [ -n "$__pebble_pid" ] && [ "$__pebble_pid" != "0" ] && [ "$__pebble_pid" != "1" ]; do',
    '    __pebble_value=""',
    '    if [ -r "/proc/$__pebble_pid/environ" ]; then',
    '      __pebble_value=$(tr "\\000" "\\n" < "/proc/$__pebble_pid/environ" 2>/dev/null | sed -n "s/^${__pebble_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__pebble_value" ]; then',
    '      __pebble_value=$(ps eww -p "$__pebble_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__pebble_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__pebble_value" ]; then',
    '      printf "%s\\n" "$__pebble_value"',
    '      return 0',
    '    fi',
    '    __pebble_pid=$(ps -o ppid= -p "$__pebble_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__pebble_fill_from_ancestor() {',
    '  __pebble_name="$1"',
    '  case "$__pebble_name" in',
    '    PEBBLE_AGENT_HOOK_ENDPOINT) [ -z "${PEBBLE_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    PEBBLE_AGENT_HOOK_PORT) [ -z "${PEBBLE_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    PEBBLE_AGENT_HOOK_TOKEN) [ -z "${PEBBLE_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    PEBBLE_AGENT_HOOK_ENV) [ -z "${PEBBLE_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    PEBBLE_AGENT_HOOK_VERSION) [ -z "${PEBBLE_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    PEBBLE_PANE_KEY) [ -z "${PEBBLE_PANE_KEY:-}" ] || return 0 ;;',
    '    PEBBLE_TAB_ID) [ -z "${PEBBLE_TAB_ID:-}" ] || return 0 ;;',
    '    PEBBLE_WORKTREE_ID) [ -z "${PEBBLE_WORKTREE_ID:-}" ] || return 0 ;;',
    '    PEBBLE_AGENT_LAUNCH_TOKEN) [ -z "${PEBBLE_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __pebble_value=$(__pebble_read_ancestor_var "$__pebble_name") || return 0',
    '  [ -n "$__pebble_value" ] && export "$__pebble_name=$__pebble_value"',
    '}',
    '__pebble_endpoint_value() {',
    '  __pebble_endpoint_name="$1"',
    '  __pebble_endpoint_path="$2"',
    '  sed -n "s/^${__pebble_endpoint_name}=//p" "$__pebble_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__pebble_fill_from_endpoint_file() {',
    '  __pebble_endpoint_path="$1"',
    '  [ -r "$__pebble_endpoint_path" ] || return 0',
    '  __pebble_endpoint_port=$(__pebble_endpoint_value PEBBLE_AGENT_HOOK_PORT "$__pebble_endpoint_path")',
    '  if [ -n "${PEBBLE_AGENT_HOOK_PORT:-}" ] && [ -n "$__pebble_endpoint_port" ] && [ "$__pebble_endpoint_port" != "$PEBBLE_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __pebble_endpoint_name in AGENT_HOOK_PORT AGENT_HOOK_TOKEN AGENT_HOOK_ENV AGENT_HOOK_VERSION; do',
    '    eval "__pebble_current=\\${PEBBLE_$__pebble_endpoint_name:-}"',
    '    [ -z "$__pebble_current" ] || continue',
    '    __pebble_endpoint_value=$(__pebble_endpoint_value "PEBBLE_$__pebble_endpoint_name" "$__pebble_endpoint_path")',
    '    [ -n "$__pebble_endpoint_value" ] && export "PEBBLE_$__pebble_endpoint_name=$__pebble_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has Pebble pane/hook metadata, so recover it before posting.',
    'for __pebble_name in PEBBLE_AGENT_HOOK_ENDPOINT PEBBLE_AGENT_HOOK_PORT PEBBLE_AGENT_HOOK_TOKEN PEBBLE_AGENT_HOOK_ENV PEBBLE_AGENT_HOOK_VERSION PEBBLE_PANE_KEY PEBBLE_TAB_ID PEBBLE_WORKTREE_ID PEBBLE_AGENT_LAUNCH_TOKEN; do',
    '  __pebble_fill_from_ancestor "$__pebble_name"',
    'done',
    'if [ -n "$PEBBLE_AGENT_HOOK_ENDPOINT" ] && [ -r "$PEBBLE_AGENT_HOOK_ENDPOINT" ]; then',
    '  __pebble_fill_from_endpoint_file "$PEBBLE_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# PEBBLE_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$PEBBLE_AGENT_HOOK_TOKEN" ] && [ -n "$PEBBLE_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/pebble-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/pebble-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/pebble-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/pebble-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/pebble/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/pebble/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^PEBBLE_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$PEBBLE_AGENT_HOOK_PORT" ]; then',
    '      __pebble_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$PEBBLE_AGENT_HOOK_PORT" ] || [ -z "$PEBBLE_AGENT_HOOK_TOKEN" ] || [ -z "$PEBBLE_PANE_KEY" ]; then',
    '  exit 0',
    'fi',
    'payload=$(cat)',
    'if [ -z "$payload" ]; then',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    // Why: pipe payload to curl's stdin (`payload@-`) instead of an inline
    // `payload=$VALUE` arg, so tens-of-KB tool output stays off the curl
    // command line (EDR command-line false positives). Wire body is identical.
    'printf \'%s\' "$payload" | curl -sS -X POST "http://127.0.0.1:${PEBBLE_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-Pebble-Agent-Hook-Token: ${PEBBLE_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${PEBBLE_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${PEBBLE_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${PEBBLE_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${PEBBLE_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${PEBBLE_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${PEBBLE_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload@-" >/dev/null 2>&1 || true',
    'exit 0',
    ''
  ].join('\n')
}
