#!/usr/bin/env bash
# Generate local debug signing material for HAP install (OpenHarmony-style localSign).
# HarmonyOS NEXT real devices / AppGallery may still require AGC profiles from DevEco.
# This is enough for many emulator / open debugging flows when DevEco auto-sign is unavailable.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SIGN_DIR="$ROOT/signing"
JAR="/Applications/DevEco-Studio.app/Contents/sdk/default/openharmony/toolchains/lib/hap-sign-tool.jar"
BUNDLE="nebutra.pebble.desktop"
STORE_PWD="pebble-debug"
KEY_ALIAS="pebble-debug-key"
KEY_PWD="pebble-debug"

if [[ ! -f "$JAR" ]]; then
  echo "hap-sign-tool.jar not found at $JAR" >&2
  exit 1
fi

mkdir -p "$SIGN_DIR"
cd "$SIGN_DIR"

echo "Generating keystore + certs in $SIGN_DIR …"

java -jar "$JAR" generate-keypair \
  -keyAlias "$KEY_ALIAS" \
  -keyPwd "$KEY_PWD" \
  -keyAlg ECC \
  -keySize NIST-P-256 \
  -keystoreFile "pebble-debug.p12" \
  -keystorePwd "$STORE_PWD"

java -jar "$JAR" generate-csr \
  -keyAlias "$KEY_ALIAS" \
  -keyPwd "$KEY_PWD" \
  -subject "C=CN,O=Nebutra,OU=Pebble,CN=Pebble Debug" \
  -signAlg SHA256withECDSA \
  -keystoreFile "pebble-debug.p12" \
  -keystorePwd "$STORE_PWD" \
  -outFile "pebble-debug.csr"

# Self-signed app cert using the same keystore as issuer (local debug only).
java -jar "$JAR" generate-app-cert \
  -keyAlias "$KEY_ALIAS" \
  -keyPwd "$KEY_PWD" \
  -issuer "C=CN,O=Nebutra,OU=Pebble,CN=Pebble Debug" \
  -issuerKeyAlias "$KEY_ALIAS" \
  -issuerKeyPwd "$KEY_PWD" \
  -subject "C=CN,O=Nebutra,OU=Pebble,CN=Pebble Debug" \
  -signAlg SHA256withECDSA \
  -keystoreFile "pebble-debug.p12" \
  -keystorePwd "$STORE_PWD" \
  -outForm "cert" \
  -outFile "pebble-debug.cer" \
  -issuerKeystoreFile "pebble-debug.p12" \
  -issuerKeystorePwd "$STORE_PWD" 2>/dev/null || \
java -jar "$JAR" generate-cert \
  -keyAlias "$KEY_ALIAS" \
  -keyPwd "$KEY_PWD" \
  -issuer "C=CN,O=Nebutra,OU=Pebble,CN=Pebble Debug" \
  -issuerKeyAlias "$KEY_ALIAS" \
  -issuerKeyPwd "$KEY_PWD" \
  -subject "C=CN,O=Nebutra,OU=Pebble,CN=Pebble Debug" \
  -validity 3650 \
  -keyUsage digitalSignature \
  -extKeyUsage codeSignature \
  -signAlg SHA256withECDSA \
  -keystoreFile "pebble-debug.p12" \
  -keystorePwd "$STORE_PWD" \
  -outFile "pebble-debug.cer" \
  -issuerKeystoreFile "pebble-debug.p12" \
  -issuerKeystorePwd "$STORE_PWD"

# Unsigned profile template
python3 - <<PY
import json, uuid, time
now = int(time.time())
profile = {
  "version-name": "1.0.0",
  "version-code": 1,
  "uuid": str(uuid.uuid4()),
  "type": "debug",
  "app-distribution-type": "os_app",
  "bundle-info": {
    "developer-id": "nebutra-pebble-debug",
    "development-certificate": open("pebble-debug.cer").read() if False else "",
    "distribution-certificate": "",
    "bundle-name": "$BUNDLE",
    "apl": "normal",
    "app-feature": "hos_normal_app"
  },
  "permissions": {
    "restricted-permissions": []
  },
  "debug": True,
  "issuer": "C=CN,O=Nebutra,OU=Pebble,CN=Pebble Debug",
  "validity": {
    "not-before": now - 60,
    "not-after": now + 3650 * 24 * 3600
  }
}
# Embed cert PEM if available
try:
    profile["bundle-info"]["development-certificate"] = open("pebble-debug.cer").read().replace("\\n", "")
except Exception:
    pass
open("UnsignedDebugProfile.json", "w").write(json.dumps(profile, indent=2))
print("Wrote UnsignedDebugProfile.json")
PY

# Profile signing may fail without a proper profile cert chain; capture output.
set +e
java -jar "$JAR" sign-profile \
  -keyAlias "$KEY_ALIAS" \
  -signAlg SHA256withECDSA \
  -mode localSign \
  -profileCertFile "pebble-debug.cer" \
  -inFile "UnsignedDebugProfile.json" \
  -keystoreFile "pebble-debug.p12" \
  -outFile "pebble-debug-profile.p7b" \
  -keyPwd "$KEY_PWD" \
  -keystorePwd "$STORE_PWD"
PROFILE_RC=$?
set -e

cat > "$SIGN_DIR/README.md" <<EOF
# Local debug signing material

Generated by \`scripts/generate-debug-signing.sh\`.

- storeFile: \`$SIGN_DIR/pebble-debug.p12\`
- storePassword / keyPassword: \`$STORE_PWD\`
- keyAlias: \`$KEY_ALIAS\`
- certpath: \`$SIGN_DIR/pebble-debug.cer\`
- profile: \`$SIGN_DIR/pebble-debug-profile.p7b\` (sign-profile exit $PROFILE_RC)

## Preferred path (HarmonyOS NEXT)

In DevEco Studio:
1. File → Project Structure → Signing Configs
2. Enable **Automatically generate signature**
3. Sign in with Huawei developer account if prompted

That writes trusted debug material into \`build-profile.json5\` for emulator install.

Local self-signed material may be rejected on undebuggable public emulator images.
EOF

echo "Done. See $SIGN_DIR/README.md"
ls -la "$SIGN_DIR"
