import reactDevtoolsInstallHook from './react-devtools-install-hook.js?raw'

const MAX_DEPTH = 8
const MAX_KEYS = 100

const pebbleReactInspectionBridge = `(()=>{const hook=globalThis.__REACT_DEVTOOLS_GLOBAL_HOOK__;if(!hook||hook.__pebble)return;const roots=new Map(),state={nextId:1,recording:false,renders:new Map()};const name=f=>f.elementType?.displayName||f.type?.displayName||f.elementType?.name||f.type?.name||(typeof f.type==='string'?f.type:null)||'Anonymous';const brief=v=>v==null?String(v):typeof v==='function'?'fn()':typeof v==='object'?(Array.isArray(v)?'Array('+v.length+')':'{'+Object.keys(v).slice(0,3).join(', ')+'}') :String(v).slice(0,60);const visit=f=>{for(let n=f;n;n=n.sibling){n.__pebbleFiberId??=state.nextId++;if(state.recording){const prior=n.alternate,did=!prior||n.flags>0||n.memoizedProps!==prior.memoizedProps||n.memoizedState!==prior.memoizedState;if(did){const entry=state.renders.get(n.__pebbleFiberId)||{fiberId:n.__pebbleFiberId,name:name(n),mounts:0,renders:0,totalTime:0,selfTime:0,domMutations:0,changes:[]};prior?entry.renders++:entry.mounts++;entry.totalTime+=Number(n.actualDuration)||0;let childTime=0;for(let c=n.child;c;c=c.sibling)childTime+=Number(c.actualDuration)||0;entry.selfTime+=Math.max(0,(Number(n.actualDuration)||0)-childTime);if(!prior)entry.changes.push({type:'mount'});else{const keys=new Set([...Object.keys(prior.memoizedProps||{}),...Object.keys(n.memoizedProps||{})]);for(const k of keys)if(k!=='children'&&prior.memoizedProps?.[k]!==n.memoizedProps?.[k]&&entry.changes.length<50)entry.changes.push({type:'props',name:k,prev:brief(prior.memoizedProps?.[k]),next:brief(n.memoizedProps?.[k])});if(prior.memoizedState!==n.memoizedState&&entry.changes.length<50)entry.changes.push({type:'state',name:'hooks',prev:brief(prior.memoizedState),next:brief(n.memoizedState)})}if((n.flags&6)>0)entry.domMutations++;state.renders.set(n.__pebbleFiberId,entry)}}if(n.child)visit(n.child)}};hook.__pebble={roots,state,name,visit};const original=hook.onCommitFiberRoot?.bind(hook);hook.onCommitFiberRoot=function(id,root){const result=original?.(...arguments);const set=roots.get(id)||new Set();set.add(root);roots.set(id,set);visit(root.current);return result};for(const id of hook.renderers?.keys?.()||[])for(const root of hook.getFiberRoots?.(id)||[]){const set=roots.get(id)||new Set();set.add(root);roots.set(id,set);visit(root.current)}})()`

export const TAURI_REACT_HOOK_SCRIPT = `${reactDevtoolsInstallHook}\n;${pebbleReactInspectionBridge}`

const PRELUDE = `(()=>{const h=globalThis.__REACT_DEVTOOLS_GLOBAL_HOOK__,p=h?.__pebble;if(!p)throw Error('React DevTools hook not installed; relaunch with --enable react-devtools');const fibers=[];const walk=f=>{for(let n=f;n;n=n.sibling){n.__pebbleFiberId??=p.state.nextId++;fibers.push(n);if(n.child)walk(n.child)}};for(const roots of p.roots.values())for(const root of roots)walk(root.current);`

const DEVTOOLS_TREE_EXPRESSION = `(async()=>{const h=globalThis.__REACT_DEVTOOLS_GLOBAL_HOOK__;const interfaces=[...(h?.rendererInterfaces?.values?.()||[])];if(!interfaces.length)return null;const batches=[];const emit=h.emit;h.emit=function(event,payload){if(event==='operations')batches.push(Array.from(payload));return emit.apply(h,arguments)};try{for(const ri of interfaces)ri.flushInitialOperations?.();await new Promise(r=>setTimeout(r,25))}finally{h.emit=emit}const nodes=[];for(const ops of batches){let i=2;const strings=[null],end=++i+ops[i-1];while(i<end){const len=ops[i++];strings.push(String.fromCodePoint(...ops.slice(i,i+len)));i+=len}while(i<ops.length){const op=ops[i];if(op===1){const id=ops[i+1],type=ops[i+2];i+=3;if(type===11){nodes.push({id,type,name:null,key:null,parent:0});i+=4}else{nodes.push({id,type,name:strings[ops[i+2]]||null,key:strings[ops[i+3]]||null,parent:ops[i]});i+=5}}else if(op===2)i+=2+ops[i+1];else if(op===3)i+=3+ops[i+2];else if(op===4)i+=3;else if(op===5)i+=4;else if(op===6)i++;else if(op===7)i+=3;else if(op===8){const n=ops[i+5];i+=6+(n===-1?0:n*4)}else if(op===9)i+=2+ops[i+1];else if(op===10)i+=3+ops[i+2];else if(op===11){const n=ops[i+2];i+=3+(n===-1?0:n*4)}else if(op===12){i++;const count=ops[i++];for(let c=0;c<count;c++){i+=4;const env=ops[i++];i+=env}}else if(op===13)i+=2;else i++}}return nodes.slice(0,10000)})()`

function devtoolsInspectExpression(id: number): string {
  return `(()=>{const h=globalThis.__REACT_DEVTOOLS_GLOBAL_HOOK__;for(const ri of h?.rendererInterfaces?.values?.()||[]){if(!ri.hasElementWithId?.(${id}))continue;const result=ri.inspectElement(1,${id},null,true);if(!result||result.type!=='full-data')throw Error('React DevTools inspect failed: '+(result?.type||'empty'));const v=result.value,read=x=>x?.data??x??null;const owners=Array.isArray(v.owners)?v.owners.map(o=>({id:o.id,name:o.displayName||'Anonymous'})):[];const source=Array.isArray(v.source)?[v.source[1]??null,v.source[2]??null,v.source[3]??null]:null;const props=read(v.props),hooks=read(v.hooks),state=read(v.state),name=ri.getDisplayNameForElementID?.(${id})||'Anonymous';return JSON.stringify({fiberId:${id},devtoolsElementId:${id},idSpace:'react-devtools',name,props,hooks,state,context:read(v.context),owners,source,debugInfoAvailable:true,text:name+' #${id}\\nprops: '+JSON.stringify(props)+'\\nhooks: '+JSON.stringify(hooks)+'\\nstate: '+JSON.stringify(state)})}return null})()`
}

export function buildReactInspectionExpression(action: string, args: string[]): string {
  if (action === 'tree') {
    return `(async()=>{const official=await ${DEVTOOLS_TREE_EXPRESSION};if(official)return JSON.stringify(official);return ${PRELUDE}return JSON.stringify(fibers.slice(0,10000).map((f,index)=>({id:f.__pebbleFiberId,parent:f.return?.__pebbleFiberId??null,depth:(()=>{let d=0,n=f.return;while(n){d++;n=n.return}return d})(),name:p.name(f),index,idSpace:'pebble-fiber'})))})()})()`
  }
  if (action === 'inspect') {
    const id = readFiberId(args[0])
    return `(()=>{const official=${devtoolsInspectExpression(id)};if(official)return official;return ${PRELUDE}const f=fibers.find(n=>n.__pebbleFiberId===${id});if(!f)throw Error('React fiber ${id} was not found');const clean=(v,d=0,s=new WeakSet())=>{if(v==null||typeof v==='string'||typeof v==='number'||typeof v==='boolean')return v;if(typeof v==='function')return '[Function '+(v.name||'anonymous')+']';if(typeof v!=='object')return String(v);if(d>=${MAX_DEPTH})return '[Max depth]';if(s.has(v))return '[Circular]';s.add(v);if(Array.isArray(v))return v.slice(0,${MAX_KEYS}).map(x=>clean(x,d+1,s));const o={};for(const k of Object.keys(v).slice(0,${MAX_KEYS}))try{o[k]=clean(v[k],d+1,s)}catch{o[k]='[Unreadable]'}return o};let hooks=[],n=f.memoizedState,i=0;const hookTypes=Array.isArray(f._debugHookTypes)?f._debugHookTypes:[];while(n&&i<100){hooks.push({id:i,name:hookTypes[i]||null,value:clean(n.memoizedState),debugInfoAvailable:Boolean(hookTypes[i])});n=n.next;i++}const owners=[];for(let o=f.return;o;o=o.return){const name=p.name(o);if(name!=='Anonymous')owners.push({id:o.__pebbleFiberId,name})}const raw=f._debugSource??f._debugOwner?._debugSource??null;const source=raw?[raw.fileName??raw[0]??null,raw.lineNumber??raw[1]??null,raw.columnNumber??raw[2]??null]:null;const props=clean(f.memoizedProps),state=clean(f.memoizedState);const lines=[p.name(f)+' #'+${id},'props: '+JSON.stringify(props),'hooks: '+JSON.stringify(hooks),'state: '+JSON.stringify(state)];if(owners.length)lines.push('rendered by: '+owners.map(o=>o.name).join(' > '));return JSON.stringify({fiberId:${id},idSpace:'pebble-fiber',name:p.name(f),props,state,hooks,owners,source,debugInfoAvailable:Boolean(source||hookTypes.length),text:lines.join('\\n')})})()})()`
  }
  if (action === 'renders') {
    const operation = args[0]
    if (operation === 'start') {
      return `${PRELUDE}p.state.renders.clear();p.state.startedAt=performance.now();p.state.recording=true;return JSON.stringify({recording:true,message:'recording renders - interact with the page, then run react renders stop'})})()`
    }
    if (operation === 'stop') {
      return `${PRELUDE}p.state.recording=false;const components=[...p.state.renders.values()].slice(0,200).map(e=>({name:e.name,count:e.mounts+e.renders,mounts:e.mounts,reRenders:e.renders,instanceCount:1,totalTime:e.totalTime||0,selfTime:e.selfTime||0,domMutations:e.domMutations||0,changes:e.changes||[],changeSummary:(e.changes||[]).reduce((o,c)=>(o[c.type+(c.name?' ('+c.name+')':'')]=(o[c.type+(c.name?' ('+c.name+')':'')]||0)+1,o),{})}));return JSON.stringify({elapsed:Math.round((performance.now()-(p.state.startedAt||performance.now())))/1000,fps:{avg:0,min:0,max:0,drops:0},totalRenders:components.reduce((s,c)=>s+c.count,0),totalMounts:components.reduce((s,c)=>s+c.mounts,0),totalReRenders:components.reduce((s,c)=>s+c.reRenders,0),totalComponents:components.length,components})})()`
    }
  }
  if (action === 'suspense') {
    const onlyDynamic = args.includes('--only-dynamic')
    return `${PRELUDE}const rows=fibers.filter(f=>f.tag===13).map(f=>{const raw=f._debugSource??f._debugOwner?._debugSource??null;const owners=[];for(let o=f.return;o;o=o.return){const name=p.name(o);if(name!=='Anonymous')owners.push(name)}const isSuspended=f.memoizedState!==null;const suspendedBy=[];if(isSuspended&&f.child)suspendedBy.push({name:p.name(f.child),reason:'pending descendant'});const unknownSuspenders=isSuspended&&suspendedBy.length===0?(raw?'thrown Promise or missing use() tracking':'production build (no debug info)'):null;const classification=!isSuspended?'ready':unknownSuspenders?'unknown-suspender':'tracked-suspender';const recommendation=classification==='ready'?'No action required.':classification==='tracked-suspender'?'Inspect the listed suspender and move data loading to the nearest intentional boundary.':'Use a React development build and prefer use() or framework loaders over throwing an untracked Promise.';return{id:f.__pebbleFiberId,parentID:f.return?.__pebbleFiberId??0,name:p.name(f),isSuspended,environments:[],suspendedBy,unknownSuspenders,owners,jsxSource:raw?[raw.fileName??null,raw.lineNumber??null,raw.columnNumber??null]:null,dynamic:isSuspended||f.alternate?.memoizedState!==f.memoizedState,classification,recommendation}});const boundaries=${onlyDynamic}?rows.filter(r=>r.dynamic):rows;return JSON.stringify({boundaries})})()`
  }
  throw new Error(`React inspection action is not migrated: ${action}`)
}

function readFiberId(value: string | undefined): number {
  const id = Number(value)
  if (!Number.isSafeInteger(id) || id <= 0) {
    throw new Error('React fiber id must be positive.')
  }
  return id
}
