package runtimecore

import (
	"database/sql"
	"encoding/json"
	"strings"
)

// Why: the vault row clamps the first ask to two lines, and the field ships in
// every scan result, so the scanner stores a preview-sized slice rather than an
// unbounded transcript paste. Matches the 220-char preview-message cap.
const aiVaultFirstUserPromptLimit = 220

// Mirror of HARNESS_INJECTED_TURN_PREFIXES in
// packages/product-core/shared/harness-injected-user-turns.ts. Keep both lists
// in step: the renderer falls back to preview turns when the scanner stored no
// prompt, and the two paths must agree on what counts as a written ask.
var aiVaultInjectedUserTurnPrefixes = []string{
	"<task-notification>",
	"<system-reminder>",
	"<local-command-stdout>",
	"<local-command-caveat>",
	"<command-name>",
	"<command-message>",
	"<command-args>",
	"<bash-",
	"[request interrupted",
	"caveat: the messages below were generated by the user while running local commands",
	"this session is being continued from a previous conversation",
}

// captureAiVaultFirstUserPrompt records the session's first written user turn.
//
// Why: the preview window keeps only the last six messages, so on any session
// longer than that the opening ask — the one thing that says what the session
// is for — has already slid out by the time the row renders.
func captureAiVaultFirstUserPrompt(session *AiVaultSession, role, text string) {
	if session.FirstUserPrompt != nil || normalizeAiVaultRole(role) != "user" {
		return
	}
	if prompt := aiVaultFirstUserPromptText(text); prompt != "" {
		session.FirstUserPrompt = &prompt
	}
}

// aiVaultFirstUserPromptText returns "" when the turn carries no visible text or
// is harness machinery replayed as a user turn.
func aiVaultFirstUserPromptText(text string) string {
	compacted := compactAiVaultText(text, aiVaultFirstUserPromptLimit)
	if compacted == "" || isAiVaultInjectedUserTurn(compacted) {
		return ""
	}
	return compacted
}

// readOpenCodeSQLiteFirstUserPrompt fills the opening ask from the oldest text
// parts of an OpenCode session database.
//
// Why a second query: the preview query reads the newest five parts, so for any
// session longer than that the opening ask is not in its result set at all and
// the row would otherwise label a mid-session turn as the first prompt. The row
// cap keeps this bounded while still stepping over leading tool/reasoning parts.
func readOpenCodeSQLiteFirstUserPrompt(db *sql.DB, session *AiVaultSession) {
	rows, err := db.Query(`SELECT m.data, p.data
		FROM message m JOIN part p ON p.message_id = m.id
		WHERE m.session_id = ? ORDER BY p.time_created ASC LIMIT 20`, session.SessionID)
	if err != nil {
		return
	}
	defer rows.Close()
	for rows.Next() {
		var messageJSON, partJSON string
		if rows.Scan(&messageJSON, &partJSON) != nil {
			return
		}
		var message, part map[string]any
		if json.Unmarshal([]byte(messageJSON), &message) != nil ||
			json.Unmarshal([]byte(partJSON), &part) != nil {
			continue
		}
		if firstString(message, "role") != "user" || firstString(part, "type") != "text" {
			continue
		}
		if prompt := aiVaultFirstUserPromptText(firstString(part, "text")); prompt != "" {
			session.FirstUserPrompt = &prompt
			return
		}
	}
}

func isAiVaultInjectedUserTurn(text string) bool {
	normalized := strings.ToLower(strings.TrimSpace(text))
	if normalized == "" {
		return false
	}
	for _, prefix := range aiVaultInjectedUserTurnPrefixes {
		if strings.HasPrefix(normalized, prefix) {
			return true
		}
	}
	return false
}
